"""Ajout de original_size à File

Revision ID: 65b0adac0653
Revises: 84ad926be8ab
Create Date: 2024-04-07 10:51:26.995898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b0adac0653'
down_revision = '84ad926be8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('compressed_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('compressed_size')
        batch_op.drop_column('original_size')

    # ### end Alembic commands ###
