"""Ajout last_opened à File

Revision ID: 84ad926be8ab
Revises: fa1623b30149
Create Date: 2024-04-07 00:36:17.681620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ad926be8ab'
down_revision = 'fa1623b30149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_opened', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('last_opened')

    # ### end Alembic commands ###
