"""Ajout de la colonne azure_blob_path

Revision ID: af19bc56f329
Revises: da7c42e2f500
Create Date: 2024-11-26 11:07:26.381667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af19bc56f329'
down_revision = 'da7c42e2f500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('azure_blob_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('azure_blob_path')

    # ### end Alembic commands ###
